def count_occurence(source,find,l):
	count=int(0)
	for i in range(len(source)):
		temp=source[i:(i+(l))]
		# print(temp)
		if((temp)==(find)):
			count+=1
	return count
s="MWULNKBNHHUBWRHBXMHYAOUQVSNHWVZMCWNQWPLMAWGHIFJHDBQWNLNMWSWCUWAWCMCWDIBNLFZUEYLOENHYDDXHPZZCNKMADAKNQWMRMEJHGVOCMXKAWNKVFNHYDDXHPZZCNKMADAKZROYFOAAMLIFNFODSNHWVSNHWNYDMWWQJVOZFXMHOSXUONMWXDXTRYYZFQYPDZLFDNERWDGBUUQIUWASMAKFHHECBHVSNHWXMWUVNGVYWCMCCWDECBHJZUSVTECYPVOCCQBUWNKZIXLOYMUFRRUWAWCQJAHIFCIEZONLWVUWIIOTNWRIENKXZZLYVJRRNVVOCCRIEQIZZHNLLAFQYDBQWNLNZXNWCQXHOTMLNRMFQYQDFAYTPUAYVOTJNWCQJAHIFLUQMQJMRIGWXHMGWWHMFJCQOKCBLNOJFONRXLDIMPYQOFQUWXMWHROAWFBVEBYVNUCMHIHRLRIYNHWVZMGDFQYLHYULNLJZBVXOMUMRZHJFXVFNCWNBAYGDOCCRIEJHGVPJJWWMBYGJZRNVVEBYVNYNHWIMCOUVXUUQBGJAHKDXWHNERHJBUEYVHMLBLIQBNKZMKCODFHNRMQJXDIPDHGZDBNDIPQOPVZUUQBGJAH"
trigram={}
for i in range(len(s)):
	y=trigram.keys()
	tri=s[i:(i+3)]
	if(tri not in y):
		trigram[tri]=[count_occurence(s,tri,3),i]
	else:
		trigram[tri].append(i)

ind=trigram.keys()
most_occuring=[]
for i in ind:
	if(trigram[i][0]<3):
		continue
	else:
		most_occuring.append(i)
		print(i,end=',')
		print(trigram[i])		
